ServerName localhost

Alias /public-files/ephemerides/ "/usr/local/apache2/htdocs/public-files/ephemerides/"

<Directory "/usr/local/apache2/htdocs/public-files/ephemerides/">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
